### ISSUE TITLE
easily breaks with non-standard input

### ISSUE THREAD

**Issue by akhepcat** [cburgmer/upsidedown#3]
echo 'ß' | upsidedown 
Traceback (most recent call last):
  File "/usr/local/bin/upsidedown", line 9, in <module>
    load_entry_point('upsidedown==0.3', 'console_scripts', 'upsidedown')()
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 135, in main
    output.append(transform(line).encode(default_encoding))
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 101, in transform
    string = string.replace(character, transliterations[character])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 0: ordinal not in range(128)

echo '§' | upsidedown 
Traceback (most recent call last):
  File "/usr/local/bin/upsidedown", line 9, in <module>
    load_entry_point('upsidedown==0.3', 'console_scripts', 'upsidedown')()
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 135, in main
    output.append(transform(line).encode(default_encoding))
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 101, in transform
    string = string.replace(character, transliterations[character])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 0: ordinal not in range(128)

echo 'ª' | upsidedown 
Traceback (most recent call last):
  File "/usr/local/bin/upsidedown", line 9, in <module>
    load_entry_point('upsidedown==0.3', 'console_scripts', 'upsidedown')()
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 135, in main
    output.append(transform(line).encode(default_encoding))
  File "/usr/local/lib/python2.7/dist-packages/upsidedown.py", line 101, in transform
    string = string.replace(character, transliterations[character])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 0: ordinal not in range(128)

...among others.

Input should deal with this correctly..

**Comment by jaraco** [comment]
Reviewing this ticket, I don't think it's an issue with upsidedown, but is more of an issue with configuring the shell/environment for the expected encoding. Therefore, it's more of a support request than a bug that needs fixing. Given there hasn't been activity for years, and that systems may have improved support for this, and that most users can probably use Python 3 these days, I'm going to close this... but feel free to revive the conversation if there's more work to be done.
